local util = require "util"
local dumptable = require "dumptable"

local fmt_file_header = [[
-- Code generated by sprotodump. PLEASE DO NOT EDIT.

return ]]

local function main(_, build, param)
    local outfile = param.outfile or "sproto_list.lua"
    local out = fmt_file_header .. dumptable(build)
    util.write_file(outfile, out, "w")
end

return main
